// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuk7-OvkXK4AYySDgvjO3eEByJvJ87w88',
    appId: '1:101794979262:web:7ca4824c51990fdb916def',
    messagingSenderId: '101794979262',
    projectId: 'techbes-app',
    authDomain: 'techbes-app.firebaseapp.com',
    storageBucket: 'techbes-app.firebasestorage.app',
    measurementId: 'G-NPRMLY8PTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZnf9mZ9y9Kr64qEFxmdbgjRz8igfxTI',
    appId: '1:101794979262:android:cbc3f53a14f58135916def',
    messagingSenderId: '101794979262',
    projectId: 'techbes-app',
    storageBucket: 'techbes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAf0ALhvrjQhIv3mkVTKghWcvOuzMRs90',
    appId: '1:101794979262:ios:b3c6183412f5b181916def',
    messagingSenderId: '101794979262',
    projectId: 'techbes-app',
    storageBucket: 'techbes-app.firebasestorage.app',
    iosBundleId: 'com.example.technicianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAf0ALhvrjQhIv3mkVTKghWcvOuzMRs90',
    appId: '1:101794979262:ios:b3c6183412f5b181916def',
    messagingSenderId: '101794979262',
    projectId: 'techbes-app',
    storageBucket: 'techbes-app.firebasestorage.app',
    iosBundleId: 'com.example.technicianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuk7-OvkXK4AYySDgvjO3eEByJvJ87w88',
    appId: '1:101794979262:web:5e1021854bfed0ad916def',
    messagingSenderId: '101794979262',
    projectId: 'techbes-app',
    authDomain: 'techbes-app.firebaseapp.com',
    storageBucket: 'techbes-app.firebasestorage.app',
    measurementId: 'G-TLD4BVXZ1T',
  );
}
